-- =========================================================
-- BLINKIT GROCERY SALES ANALYSIS
-- SQL DATA ANALYST PROJECT
-- =========================================================

CREATE DATABASE IF NOT EXISTS blinkit;
USE blinkit;

DROP TABLE IF EXISTS blinkit_sales;

CREATE TABLE blinkit_sales (
    item_fat_content VARCHAR(20),
    item_identifier VARCHAR(20),
    item_type VARCHAR(50),
    outlet_establishment_year INT,
    outlet_identifier VARCHAR(20),
    outlet_location_type VARCHAR(20),
    outlet_size VARCHAR(20),
    outlet_type VARCHAR(50),
    item_visibility DOUBLE,
    item_weight DOUBLE,
    sales DOUBLE,
    rating DOUBLE
);

-- Load cleaned dataset
LOAD DATA INFILE
'D:/ProgramData/MySQL/MySQL Server 8.0/Uploads/blinkit_cleaned.csv'
INTO TABLE blinkit_sales
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;


-- =========================================================
-- 1. DATA VALIDATION
-- =========================================================

-- Q1. How many records are present in the dataset?

SELECT COUNT(*) AS total_rows
FROM blinkit_sales;


-- Q2. What does the dataset look like?

SELECT *
FROM blinkit_sales
LIMIT 10;


-- Q3. What are the columns and their data types?

DESCRIBE blinkit_sales;


-- =========================================================
-- 2. KEY PERFORMANCE INDICATORS
-- =========================================================

-- Q4. What is the total sales generated?

SELECT
    CAST(SUM(sales) / 1000000 AS DECIMAL(10,2)) AS total_sales_millions
FROM blinkit_sales;


-- Q5. What is the average sales per record?

SELECT
    ROUND(AVG(sales), 2) AS avg_sales
FROM blinkit_sales;


-- Q6. What is the total sales generated by Low Fat products?

SELECT
    CAST(SUM(sales) / 1000000 AS DECIMAL(10,2)) AS total_sales_millions
FROM blinkit_sales
WHERE item_fat_content = 'Low Fat';


-- Q7. What is the total sales generated by Regular products?

SELECT
    CAST(SUM(sales) / 1000000 AS DECIMAL(10,2)) AS total_sales_millions
FROM blinkit_sales
WHERE item_fat_content = 'Regular';


-- Q8. What is the average customer rating?

SELECT
    ROUND(AVG(rating), 2) AS avg_rating
FROM blinkit_sales;


-- Q9. How many different item types are present?

SELECT
    COUNT(DISTINCT item_type) AS total_item_types
FROM blinkit_sales;


-- Q10. How many outlets are present?

SELECT
    COUNT(DISTINCT outlet_identifier) AS total_outlets
FROM blinkit_sales;


-- Q11. What is the average item weight?

SELECT
    ROUND(AVG(item_weight), 2) AS avg_item_weight
FROM blinkit_sales;


-- =========================================================
-- 3. PRODUCT ANALYSIS
-- =========================================================

-- Q12. Which item types generate the highest total sales?

SELECT
    item_type,
    ROUND(SUM(sales), 2) AS total_sales
FROM blinkit_sales
GROUP BY item_type
ORDER BY total_sales DESC;


-- Q13. How do sales compare across outlet types?

SELECT
    outlet_type,
    ROUND(SUM(sales), 2) AS total_sales
FROM blinkit_sales
GROUP BY outlet_type
ORDER BY total_sales DESC;


-- Q14. Which outlet location type generates the highest sales?

SELECT
    outlet_location_type,
    ROUND(SUM(sales), 2) AS total_sales
FROM blinkit_sales
GROUP BY outlet_location_type
ORDER BY total_sales DESC;


-- Q15. How do sales vary by outlet size?

SELECT
    outlet_size,
    ROUND(SUM(sales), 2) AS total_sales
FROM blinkit_sales
GROUP BY outlet_size
ORDER BY total_sales DESC;


-- Q16. How do sales and average sales compare by fat content?

SELECT
    item_fat_content,
    ROUND(SUM(sales), 2) AS total_sales,
    ROUND(AVG(sales), 2) AS avg_sales
FROM blinkit_sales
GROUP BY item_fat_content
ORDER BY total_sales DESC;


-- Q17. Which item types have the highest number of records,
-- total sales, and average sales?

SELECT
    item_type,
    COUNT(*) AS total_records,
    ROUND(SUM(sales), 2) AS total_sales,
    ROUND(AVG(sales), 2) AS avg_sales
FROM blinkit_sales
GROUP BY item_type
ORDER BY total_sales DESC;


-- =========================================================
-- 4. OUTLET ANALYSIS
-- =========================================================

-- Q18. What is the sales performance of each outlet?

SELECT
    outlet_identifier,
    outlet_type,
    outlet_location_type,
    outlet_size,
    ROUND(SUM(sales), 2) AS total_sales,
    ROUND(AVG(sales), 2) AS avg_sales,
    COUNT(*) AS total_records
FROM blinkit_sales
GROUP BY
    outlet_identifier,
    outlet_type,
    outlet_location_type,
    outlet_size
ORDER BY total_sales DESC;


-- Q19. Which item types generate more than 100,000 in total sales?

SELECT
    item_type,
    ROUND(SUM(sales), 2) AS total_sales
FROM blinkit_sales
GROUP BY item_type
HAVING SUM(sales) > 100000
ORDER BY total_sales DESC;


-- =========================================================
-- 5. CTE ANALYSIS
-- =========================================================

-- Q20. What is the total sales generated by each item type
-- using a Common Table Expression?

WITH item_sales AS (
    SELECT
        item_type,
        SUM(sales) AS total_sales
    FROM blinkit_sales
    GROUP BY item_type
)
SELECT *
FROM item_sales
ORDER BY total_sales DESC;


-- =========================================================
-- 6. CASE WHEN ANALYSIS
-- =========================================================

-- Q21. How many records fall into High, Medium,
-- and Low Sales categories?

SELECT
    CASE
        WHEN sales >= 200 THEN 'High Sales'
        WHEN sales >= 100 THEN 'Medium Sales'
        ELSE 'Low Sales'
    END AS sales_category,
    COUNT(*) AS total_records
FROM blinkit_sales
GROUP BY sales_category
ORDER BY total_records DESC;


-- Q22. How can outlets be classified based on
-- their total sales performance?

SELECT
    outlet_identifier,
    ROUND(SUM(sales), 2) AS total_sales,
    CASE
        WHEN SUM(sales) >= 115000 THEN 'High Performing'
        WHEN SUM(sales) >= 90000 THEN 'Medium Performing'
        ELSE 'Low Performing'
    END AS performance_category
FROM blinkit_sales
GROUP BY outlet_identifier
ORDER BY total_sales DESC;


-- Q23. How many products fall into Low, Medium,
-- and High visibility categories?

SELECT
    CASE
        WHEN item_visibility < 0.05 THEN 'Low Visibility'
        WHEN item_visibility < 0.10 THEN 'Medium Visibility'
        ELSE 'High Visibility'
    END AS visibility_category,
    COUNT(*) AS total_records
FROM blinkit_sales
GROUP BY visibility_category
ORDER BY total_records DESC;


-- Q24. How do sales differ across visibility categories?

SELECT
    CASE
        WHEN item_visibility < 0.05 THEN 'Low Visibility'
        WHEN item_visibility < 0.10 THEN 'Medium Visibility'
        ELSE 'High Visibility'
    END AS visibility_category,
    COUNT(*) AS total_records,
    ROUND(SUM(sales), 2) AS total_sales,
    ROUND(AVG(sales), 2) AS avg_sales
FROM blinkit_sales
GROUP BY visibility_category
ORDER BY avg_sales DESC;


-- =========================================================
-- 7. SUBQUERY ANALYSIS
-- =========================================================

-- Q25. Which item types have average sales higher
-- than the overall average sales?

SELECT
    item_type,
    ROUND(AVG(sales), 2) AS avg_sales
FROM blinkit_sales
GROUP BY item_type
HAVING AVG(sales) > (
    SELECT AVG(sales)
    FROM blinkit_sales
)
ORDER BY avg_sales DESC;


-- Q26. Which individual products have sales higher
-- than the overall average sales?

SELECT
    item_identifier,
    item_type,
    ROUND(sales, 2) AS sales
FROM blinkit_sales
WHERE sales > (
    SELECT AVG(sales)
    FROM blinkit_sales
)
ORDER BY sales DESC;


-- =========================================================
-- 8. WINDOW FUNCTION ANALYSIS
-- =========================================================

-- Q27. What is the sales ranking of each item type?

SELECT
    item_type,
    ROUND(SUM(sales), 2) AS total_sales,
    RANK() OVER (
        ORDER BY SUM(sales) DESC
    ) AS sales_rank
FROM blinkit_sales
GROUP BY item_type;


-- =========================================================
-- 9. COMBINED BUSINESS ANALYSIS
-- =========================================================

-- Q28. Which item types have both strong sales
-- and an average rating above 4?

SELECT
    item_type,
    ROUND(SUM(sales), 2) AS total_sales,
    ROUND(AVG(rating), 2) AS avg_rating
FROM blinkit_sales
GROUP BY item_type
HAVING SUM(sales) > 50000
   AND AVG(rating) > 4
ORDER BY total_sales DESC;